apiVersion: v1
kind: ConfigMap
metadata:
  name: mycm1
data:
  one: "1"
  two: "2"
  three: "3"
  testo: "bulka"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy1
  labels:
    service: mydeploy1
spec:
  replicas: 3
  selector:
    matchLabels:
      service: mydeploy1
  template:
    metadata:
      labels:
        service: mydeploy1
    spec:
      containers:
      - name: main2
        command: [ "/bin/bash", "-c", "while true; do date ; sleep 1 ; done" ]
        image: ubuntu:19.04
        env:
        - name: HELO
          value: "newValue"
        - name: EMPTYVAR1
          value: ""
        - name: EMPTYVAR2
