apiVersion: v1
kind: ConfigMap
metadata:
  name: mycm1
data:
  moloko: omlet
  aloe: aloha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy1
  labels:
    service: mydeploy1
  annotations:
    "werf.io/set-replicas-only-on-creation": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mydeploy1
  template:
    metadata:
      labels:
        service: mydeploy1
    spec:
      containers:
      - name: main
        command: [ "/bin/bash", "-c", "while true; do date ; sleep 1 ; done" ]
        image: ubuntu:18.04
        env:
        - name: HELO
          value: "TOTAL NEW"
        - name: EMPTYVAR1
          value: ""
        - name: EMPTYVAR2
