apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy1
  annotations:
    "werf.io/set-replicas-only-on-creation": "true"
    "werf.io/set-resources-only-on-creation": "true"
  labels:
    service: mydeploy1
spec:
  replicas: 4
  selector:
    matchLabels:
      service: mydeploy1
  template:
    metadata:
      labels:
        service: mydeploy1
    spec:
      containers:
      - name: main
        command: [ "/bin/bash", "-c", "while true; do date ; sleep 1 ; done" ]
        image: ubuntu:18.04
        resources:
          requests:
            memory: "256Mi"
            cpu: "70m"
          limits:
            memory: "512Mi"
            cpu: "100m"
